### ISSUE TITLE
Not retrieving all of the gift event data.

### ISSUE THREAD

**Issue by heyitsphilip** [zerodytrash/TikTok-Live-Connector#28] opened 2022-04-29 01:40 UTC
![Screenshot 2022-04-28 203629](https://user-images.githubusercontent.com/58404279/165872788-d5392526-d226-4777-9b34-f328dd897f70.png)

I've encountered an issue where it seems like it's only importing all of the data for some gift events. With others, it seems to only be importing the "sender details". I console.log() all of the data and that's all that's showing. It seems to only be happening with some users. Not sure if I'm doing something wrong.

**Comment by zerodytrash** [comment] 2022-04-29 02:19
are you using the latest version? Seems to be related to #23 but the problem is fixed in the latest version.

**Comment by heyitsphilip** [comment] 2022-04-29 16:47
That fixed it. Thank you.

**Closed** 2022-04-29 18:09 UTC
